.\"  -*- nroff -*-
.TH FORKED-DAAPD "8" "2015-12-30" "forked-daapd" "DAAP, MPD & RSP media server"
.SH NAME
forked\-daapd \- iTunes\-compatible DAAP server with MPD and RSP support
.SH SYNOPSIS
.B forked-daapd
[\fIoptions\fR]
.SH DESCRIPTION
\fBforked\-daapd\fP is a Linux/FreeBSD DAAP (iTunes) media server with support
for AirPlay devices, Apple Remote (and compatibles), MPD, Spotify, mp3 streaming
and internet radio. It allows you to share your music collection over the local
network.
.SH OPTIONS
.TP
\fB\-d\fR \fIlevel\fP
Log level (0\-5).
.TP
\fB\-D\fR \fIdom,..,dom\fP
Debug domains; available domains are: \fIconfig\fP, \fIdaap\fP,
\fIdb\fP, \fIhttpd\fP, \fImain\fP, \fImdns\fP, \fImisc\fP,
\fIrsp\fP, \fIscan\fP, \fIxcode\fP, \fIevent\fP, \fIhttp\fP, \fIremote\fP,
\fIdacp\fP, \fIffmpeg\fP, \fIartwork\fP, \fIplayer\fP, \fIraop\fP,
\fIlaudio\fP, \fIdmap\fP, \fIfdbperf\fP, \fIspotify\fP, \fIlastfm\fP,
\fIcache\fP, \fImpd\fP, \fIstream\fP.
.TP
\fB\-c\fR \fIfile\fP
Use \fIfile\fP as the configuration file.
.TP
\fB\-P\fR \fIfile\fP
Write PID to \fIfile\fP.
.TP
\fB\-f\fR
Run in the foreground.
.TP
\fB\-b\fR \fIffid\fP
\fIffid\fP to be broadcast in mDNS records.
.TP
\fB\-v\fR
Display version information.
.SH FILES
.nf
 \fI/etc/forked\-daapd.conf\fR
 \fI/var/cache/forked\-daapd\fR
.fi
.SH SEE ALSO
See \fIhttp://ejurgensen.github.io/forked-daapd/\fR for more in-depth information
about using \fBforked-daapd\fP.
