#!/bin/sh -e

action="$1"
CONF=/etc/mt-daapd.conf
PLAY=/etc/mt-daapd.playlist
CACHE=/var/cache/mt-daapd

case "$1" in
    configure)
        if [ ! -f $CONF ] ; then cp /usr/share/doc/mt-daapd/mt-daapd.conf $CONF; fi
        if [ ! -f $PLAY ] ; then cp /usr/share/doc/mt-daapd/mt-daapd.playlist $PLAY; fi
	if [ ! -d $CACHE ] ; then mkdir -p $CACHE; fi
    ;;
esac
