
#ifndef __DAAP_QUERY_H__
#define __DAAP_QUERY_H__

#include "logger.h"
#include "misc.h"

struct dmap_query_field_map {
  char *dmap_field;
  char *db_col;
  int as_int;
};


/* Generated by gperf - keep in sync, don't alter */
const struct dmap_query_field_map *
daap_query_field_lookup (register const char *str, register unsigned int len);

char *
daap_query_parse_sql(const char *daap_query);

#endif /* !__DAAP_QUERY_H__ */
